# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
            preserve_default=False,
        ),
    ]
