# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_category_budget_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='amount_saved',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
            preserve_default=False,
        ),
    ]
