# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='budget.PaymentMethod'),
            preserve_default=False,
        ),
    ]
