# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20180214_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='monthly_budgeted_amount',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchase_date',
            field=models.DateField(verbose_name=b'Purchase Date'),
        ),
    ]
