# Generated by Django 2.0.2 on 2018-02-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20180215_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purchase_date',
            field=models.DateField(verbose_name='Purchase Date'),
        ),
    ]
