# Generated by Django 2.0.2 on 2018-02-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_auto_20180216_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
    ]
