# Generated by Django 2.0.2 on 2018-03-20 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_auto_20180217_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='amount_saved',
            new_name='amount',
        ),
    ]
