# Generated by Django 2.0.2 on 2018-03-20 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_auto_20180319_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transaction_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.PaymentMethod')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.RenameField(
            model_name='savings',
            old_name='amount',
            new_name='total',
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='saving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Savings'),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Store'),
        ),
    ]
