# Generated by Django 2.0.2 on 2018-03-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_auto_20180319_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savings',
            options={'ordering': ['-monthly_budgeted_amount'], 'verbose_name_plural': 'savings'},
        ),
    ]
