# Generated by Django 2.0.2 on 2018-03-24 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_auto_20180320_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savings',
            options={'ordering': ['name'], 'verbose_name_plural': 'savings'},
        ),
    ]
